bind r source-file ~/.config/tmux/tmux.conf \; display "Config Updated"

# Unbinds
unbind C-h
unbind -n M-Left
unbind -n M-Down
unbind -n M-Up
unbind -n M-Right
unbind -n M-h
unbind -n M-j
unbind -n M-k
unbind -n M-l

# Prefix Settings
set -g prefix C-h
set -g xterm-keys on
bind C-h send-prefix

# Basic Compatibility
set  -g default-terminal "tmux-256color"
set-option -a terminal-features ',wezterm:RGB'
set -ga terminal-overrides ',wezterm:RGB,X1'
set  -g allow-passthrough on

# History
set-option -g history-limit 100000
set -s set-clipboard on
set -g mouse on

# Base 1 Indexing
set	 -g base-index 1
setw -g pane-base-index 1

# Window Management
set	 -g renumber-windows on
setw -g automatic-rename off

# Statusline
set  -g status-position	top
set  -g status-interval	5
set  -g status-left  ''
set  -g status-right '#{?#{end:TMUX_VENV_NAME},venv: #{env:TMUX_VENV_NAME} ,}#{?#{env:TMUX_GIT_BRANCH},| git: #{env:TMUX_GIT_BRANCH} ,}| [ #(sh ~/.config/tmux/tmux-battery.sh)%% ]'
setw -g status-style			          'fg=#5f5f5f bg=#000000'
set  -g pane-border-style		        'fg=#393939,bg=#000000'
set  -g pane-active-border-style	  'fg=#f2f4f8,bg=#000000'
setw -g window-status-style 		    'fg=#5f5f5f,bg=#000000'
setw -g window-status-current-style 'fg=#000000,bg=#5f5f5f,bold'
setw -g window-status-format ' #I: #W '
setw -g window-status-current-format ' #I: #W '

# Vim Motions
is_vim='ps -o state= -o comm= -t "#{pane_tty}" | grep -iqE "^[^TXZ ]+ +(\\S+/)?g?(view|n?vim?x?)(diff)?$"'

bind -n M-h			if-shell "$is_vim" "send-keys M-Right" "select-pane -R \; if -F '#{m:#{pane_current_command},*vim*}' 'send-keys Escape \":\" \"999wincmd h\" Enter'"
bind -n M-j     if-shell "$is_vim" "send-keys M-Left"  "select-pane -L \; if -F '#{m:#{pane_current_command},*vim*}' 'send-keys Escape \":\" \"999wincmd l\" Enter'"
bind -n M-k     if-shell "$is_vim" "send-keys M-Down"  "select-pane -D \; if -F '#{m:#{pane_current_command},*vim*}' 'send-keys Escape \":\" \"999wincmd k\" Enter'"
bind -n M-l     if-shell "$is_vim" "send-keys M-Up"    "select-pane -U \; if -F '#{m:#{pane_current_command},*vim*}' 'send-keys Escape \":\" \"999wincmd j\" Enter'"

# Standard Motions
bind -n M-Right if-shell "$is_vim" "send-keys M-Right" "select-pane -R \; if -F '#{m:#{pane_current_command},*vim*}' 'send-keys Escape \":\" \"999wincmd h\" Enter'"
bind -n M-Left  if-shell "$is_vim" "send-keys M-Left"  "select-pane -L \; if -F '#{m:#{pane_current_command},*vim*}' 'send-keys Escape \":\" \"999wincmd l\" Enter'"
bind -n M-Down  if-shell "$is_vim" "send-keys M-Down"  "select-pane -D \; if -F '#{m:#{pane_current_command},*vim*}' 'send-keys Escape \":\" \"999wincmd k\" Enter'"
bind -n M-Up    if-shell "$is_vim" "send-keys M-Up"    "select-pane -U \; if -F '#{m:#{pane_current_command},*vim*}' 'send-keys Escape \":\" \"999wincmd j\" Enter'"

# Page Turning
bind -n M-PgUp	previous-window
bind -n M-PgDn	next-window
bind -n M-1		select-window -t 1
bind -n M-2		select-window -t 2
bind -n M-3		select-window -t 3
bind -n M-4		select-window -t 4
bind -n M-5		select-window -t 5
bind -n M-6		select-window -t 6
bind -n M-7		select-window -t 7
bind -n M-8		select-window -t 8
bind -n M-9		select-window -t 9
bind -n M-0		select-window -t 10
bind -n M-t		split-pane -h
bind -n M-n		new-window

# Fast Session Switcher
bind l display-popup -h 80% -w 80% -E '~/.local/bin/tmux-dev-launch'
bind n command-prompt -p "New Project Name: " "run-shell '~/.local/bin/tmux-dev-new %%'"

# Pop-Up Tools
bind h display-popup -h 80% -w 80% -E 'btop'
